---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secrets-demo-secrets
  namespace: logius-moz-poc
spec:
  encryptedData:
    Secrets__SymmetricKey: AgBAGGO13tUssLHp2ptlQTo8DUTV9R0KR28Snf1Fq1As16VJcvsv/pNlC+lXnj3uZ9DPSKW3nTYYHms0pfkwVXe+MT/U62jdLUTdKxDNgZAI7hfsgG6Wch7VH9XQ1B2EEWzvvT5E5U/gNWPd4XHNGZrs1pCneVYFfTlyxOu8379UyBuajVZrRbQHizpwmW7FKgFF9HlP8VH/QFiNi725K3lQAGXfYXJIYO2zyYqRrDb099ZHZ1OXbvR1J9o/shRxj1YccJQwX2RQLTUs9JjRD2DhQqseFqRuj2cjLT0JuO6B5N51qVt2Coq+C5XXTzbxoX1CLXC1n9HRrBLid6kJlPdY24gqkU6ba5/Hrl8YR+mJS2XwctHXZrqTHaNGOQ5BLZd8q0sEnzMUpNmt+DrfOz83XNOUh1aaDwaO/gI6DUlVdLY/4dSMtArUAIurP6JeCwR7wcSuEa/Nmjy87skB7K3Sjnp7uWMSpqA7iQwlPU/Al7ow3lhNLEwpT1OzVIp8HnxqijvnLdEmEdGVmojzaS7NQtAb5urOoPYBu9Fr6NdLBzDNFIQ2LV/XnPMawLBqH5F5sMP6jDgrGnjW18XhVcpj3G9tSIVrwK+ituQ7sAbGzv/S6z73JW065zEQT1cm/gXWmlaveG1EBbwfTkKtKBLAqAt8yNyda5D5YJKYSia7aFlXJQ8qBAeE6xqQ/+9j3NS7zR/YD1KfVdHqSyUTummDJnh+cirtciTUsUGvAc0sTA==
  template:
    metadata:
      name: secrets-demo-secrets
      namespace: logius-moz-poc